sudo: false
language: node_js
node_js:
    - '16'

# Define the script to run tests and report coverage
script:
    - yarn test --coverage
    - yarn coveralls

# Configure notifications
notifications:
    email: false
